### ISSUE TITLE
File picker on splash page

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/auspice.us#25]
### Context

The current drag-and-drop interface is limiting for a number of reasons, and was primarily implemented due to simplicity. It enforces that all files are dragged on at the same time (except those files which shouldn't be, such as metadata CSVs!), and with the implementation of narratives/sidecar files in https://github.com/nextstrain/auspice.us/pull/23 there is no way to order the datasets for tangletrees. Furthermore, some users are more familiar with a "select file(s)" interfaces. [Nextclade](https://clades.nextstrain.org/) has a nice simple example of such as UI.

### Description

The following functionality is desirable, but a MVP could implement only a subset:

* [Ability to select files](https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications)
* Ability to drag on files in different stages
* Automatic grouping of dragged files into "datasets" (i.e. `X.json` and `X_measurements.json` are grouped). I'll use the term "slot" for this below.
    * This should highlight orphaned files (e.g. `X_measurements.json` where `X.json` wasn't dropped on). 
    * Bonus: some sidecars require that an entry is present in `meta.panels`. We should indicate when this is not the case, as the sidecar won't load.
* Auspice can only display two datasets. Using the slots described above, we should indicate that slots 3 onwards will not be displayed
    * Order is important (think tangletrees) so we should allow slots to be reordered. 
    * The second slot (tree) won't use tip-frequencies / measurements panels, and possibly not the root-sequence. The UI would want to indicate that these sidecar files, if present, will be unused.
* For narratives, one option would be to create a set of (possibly) empty slots for each URL path specified in the markdown.
    * I think it's reasonable to not allow a narrative to load without each slot having a dataset loaded.
    * We could think about allowing dataset names to not match the URLs so precisely, but here be 🐲 
    * Multiple narratives don't make sense for auspice.us
* Metadata CSVs currently have to be dropped on. It'd be nice to allow them to be used here, but not essential and complicated (requires digging more into auspice's internals I imagine).

**Comment by corneliusroemer** [comment]
Just came here to request this :) Wanted to load a tree on mobile where I can't drop

**Comment by victorlin** [comment]
I created #77 which simply adds a file picker on the splash page. This doesn't address most of the features in the issue description, which are more about generally handling more file loading scenarios which extends beyond initial load on the splash page.

**Comment by victorlin** [comment]
Closing this since there is a file picker now. Feel free to re-open or create separate issues for the other features.
