### ISSUE TITLE
Support https

### ISSUE THREAD

**Issue by yzhang2168** [nextstrain/auspice.us#3]
**Current Behavior**
error in opening auspice.us in browsers

**Expected behavior**
A clear and concise description of what you expected to happen instead.
open auspice

**How to reproduce**
Steps to reproduce the current behavior:
1. Open browser: Chrome, Firefox, Safari
2. https://auspice.us/
3. See error:
auspice.us sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

**Possible solution**
(optional)

**Your environment: if browsing Nextstrain online**
 - Operating system: Mac
 - Browser: Chrome, Firefox, Safari

**Your environment: if running Nextstrain locally**
 - Operating system:
 - Browser:
 - Version (e.g. `auspice 2.7.0`):

**Additional context**

**Comment by emmahodcroft** [comment]
Thanks @yzhang2168 and sorry for the confusion! Can you point to us which tutorial you were following and where this is? I can update the necessary link until we get the https working!

**Comment by yzhang2168** [comment]
https://nextstrain.github.io/ncov/setup

**Comment by emmahodcroft** [comment]
Thank you! I've changed this in our source code, and it should hopefully percolate that change up to the website shortly. @jameshadfield am I correct that happens automatically?

**Comment by jameshadfield** [comment]
Yup! (changes are now live 😄 )
