### ISSUE TITLE
Direct link to auspice.us with JSON or Newick URL?

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/auspice.us#5]
**Context**  
I would like to link to auspice.us with a URL of a Newick or JSON file, so that I can share a visualization of a tree without others having to download my tree file and drag it into auspice.us.

**Description**   
auspice.us could define a format for links, e.g.

https://auspice.us/?dataUrl=_url_

where the user can provide a JSON or Newick URL as _url_

I don't care if it looks anything like "?dataUrl=", any magical incantation will do.  :)

**Examples**  

https://auspice.us/?dataUrl=https://hgwdev.gi.ucsc.edu/~angie/example.nwk

Sorry if I've missed an obvious way to do this!  Thanks so much for providing augur, auspice and Nextstrain, they are incredibly useful.

**Comment by trvrb** [comment]
This is a fantastic suggestion @AngieHinrichs. We're looking into how to implement this now.

**Comment by AngieHinrichs** [comment]
Thanks, looking forward to it!

**Comment by AngieHinrichs** [comment]
Sounds like this has moved to [nextstrain.org PR 216](https://github.com/nextstrain/nextstrain.org/pull/216), feel free to close this one.  Thanks!

**Comment by jameshadfield** [comment]
Yup! Closing this as the functionality is now in nextstrain.org -- [docs here](https://nextstrain.org/docs/contributing/fetch-data-from-custom-urls)
