### ISSUE TITLE
tree with 36,000 tips doesn't load

### ISSUE THREAD

**Issue by DAVILIA** [nextstrain/auspice.us#74]
I have performed a json analysis with omicron and my entire tree is correct, I have managed to obtain results from all the variants on its Peru website. With Omicron, I don't know if because there are too many genomes 36,360 the page does not load and an error appears.
Please can you help me.

**Comment by jameshadfield** [comment]
Auspice isn't designed to handle such large trees, in our experience 5,000 tips is a good number to aim for. This is partly why we subsample the SC2 analyses on nextstrain.org. I suggest you try [taxonium](https://taxonium.org/) for trees this size.
